# Generated by Django 4.2.7 on 2023-12-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_orders_orderitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='crew_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
